name: flutter_project_resources
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.2

  equatable: ^2.0.5
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: ^2.0.10
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.5+3
  optional: ^6.1.0+1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  isar_generator: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
    - .env.staging
